# Generated by Django 4.0rc1 on 2022-03-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
