# Generated by Django 4.0rc1 on 2022-03-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_revenue_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
