# Generated by Django 4.0rc1 on 2022-03-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_alter_area_table_alter_city_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='average_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='economy_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='land',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
