# Generated by Django 4.0rc1 on 2022-03-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_country_average_age_country_economy_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='land',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='mayor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
