# Generated by Django 4.0.3 on 2022-03-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_area_area_type_area_chairman_area_maintain_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='country',
        ),
        migrations.AddField(
            model_name='revenue',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='country.area'),
        ),
    ]
